development:  
  adapter: postgresql
  encoding: unicode
  database: dev_creabl
  pool: 5
  username: postgres
  password:
  host: localhost

test:  
  adapter: postgresql
  encoding: unicode
  database: test_creabl
  pool: 5
  username: postgres
  password:
  host: localhost

prduction:  
  adapter: postgresql
  encoding: unicode
  database: prod_creabl
  pool: 5
  username: postgres
  password:

stage:  
  adapter: postgresql
  encoding: unicode
  database: prod_creabl
  pool: 5
  username: postgres
  password:
  host: localhost

