# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5079ba157013f2138ff3935669df90e1c6ae3634abcb6222db8036368bb9c28a947bccd788351b4c17f3dd0622936272b9c97783bdeb97c81ce5cc01305d2ea6
  stripe_publishable_key: pk_test_4ofY84F1V5vKst8sob98RWqa
  stripe_secret_key: sk_test_4DAC3vUMMMrozEAbQLBq9DoE
  mailchimp_api_key: "5301d4bebb495a967cf921d503e178eb-us14"
  mailchimp_list_id: "3d60bf4163"
  mandrill_username: "contact@wileoo.com"
  mandrill_api_key: "UnX3VvkspAI6gouxAbtdfw"
  S3_BUCKET_NAME: "lelabo-ondemand"
  AWS_ACCESS_KEY_ID: "AKIAJ747UFY3OSZX6JZA"
  AWS_SECRET_ACCESS_KEY: "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"
  AWS_REGION: "us-east-1"

test:
  secret_key_base: 3c883ea37754cac596729fa4db9197cad507c5dc78981df41e9ebdf87fb6a48567d7ec8134ac9fc7a31e74715e417b499f6950bc14aa06612212ccfe4ffe7c22
  mailchimp_api_key: "00683774b59d06e50618b5631f77d3f3-us12"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: pk_live_4AIg4HP0q4rsMTuQb4ElqW0E
  stripe_secret_key: sk_live_dNyPoBa03J8smyLy8X90BVbE
  mailchimp_api_key: "5301d4bebb495a967cf921d503e178eb-us14"
  mailchimp_list_id: "3d60bf4163"
  mandrill_username: "contact@wileoo.com"
  mandrill_api_key: "UnX3VvkspAI6gouxAbtdfw"
  S3_BUCKET_NAME: "lelabo-ondemand"
  AWS_ACCESS_KEY_ID: "AKIAJ747UFY3OSZX6JZA"
  AWS_SECRET_ACCESS_KEY: "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"
  AWS_REGION: "us-east-1"

stage:
  secret_key_base: 5079ba157013f2138ff3935669df90e1c6ae3634abcb6222db8036368bb9c28a947bccd788351b4c17f3dd0622936272b9c97783bdeb97c81ce5cc01305d2ea6
  stripe_publishable_key: pk_test_4ofY84F1V5vKst8sob98RWqa
  stripe_secret_key: sk_test_4DAC3vUMMMrozEAbQLBq9DoE
  mailchimp_api_key: "5301d4bebb495a967cf921d503e178eb-us14"
  mailchimp_list_id: "3d60bf4163"
  mandrill_username: "contact@wileoo.com"
  mandrill_api_key: "UnX3VvkspAI6gouxAbtdfw"
  S3_BUCKET_NAME: "lelabo-ondemand"
  AWS_ACCESS_KEY_ID: "AKIAJ747UFY3OSZX6JZA"
  AWS_SECRET_ACCESS_KEY: "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"
  AWS_REGION: "us-east-1"
