#!/usr/lib/env ruby
# encoding: utf-8

class ToDoListsController < ApplicationController
	respond_to :html, :js
	before_action :set_todolists, only: [:new, :destroy]

	def show
		@list = @user.to_do_lists.find(params[:id])
		@user = current_user
		@new_list = @list.tasks.build
		@to_do = @list.tasks.where(done: false).order('created_at DESC')
		@done = @list.tasks.where(done: true).order('created_at DESC')
	end

	def new
		@user = current_user
		@todolist = ToDoList.new
	end

	def create
		@todolist = ToDoList.new(to_do_lists_params)
		if @todolist.save
			redirect_to @todolist
		else
			render :new
			flash[:error] = "Une erreur a empêché la création de la liste"
		end
	end

	def update
		@todolist = ToDoList.find(params[:id])
		@todolist.update(to_do_lists_params)
		redirect_to @todolist
		respond_to do |format|
			format.html { redirect_to @todolist }
			format.js { }
		end
	end

	def destroy
		@todolist = ToDoList.find(params[:id])
		@todolist.destroy
		respond_to do |format|
			format.html { redirect_to @todolist }
			format.js { }
		end
	end

	def set_todolists
		@todolists =@user.to_do_lists.all
	end

	private

	def to_do_lists_params
		params.require(:to_do_list).permit(:title, :description, :user_id)
	end

end