class CreateBaseRecipeIngredientsJob < ActiveJob::Base
	queue_as :default

	def perform(user)
		begin
			user.ingredients.create!([
                { name: "Chocolat 70.38.30 Callebaut", protein: "3.5", carbohydrates: "24.5", fat_percent: "38", kcal: "572", ig: "25", price:"12.3" , unit: "Kg", category: "Chocolats", sugar_power: "30", alcool_percent: "", cocoa_butter_percent: "38",  salt: "",
                water_percent: "", sugar_percent: "30", dry_matter_percent: "100", cocoa_percent: "32", cocoa_total_percent: "70", provider_id: "" },
                { name: "Chocolat Saint Domingue Barry 70%", protein: "3.5", carbohydrates: "24.5", fat_percent: "41.9", kcal: "572", ig: "25", price:"14.8" , unit: "Kg", category: "Chocolats", sugar_power: "30", alcool_percent: "", cocoa_butter_percent: "41.9",  salt: "",
                water_percent: "", sugar_percent: "30", dry_matter_percent: "100", cocoa_percent: "28.1", cocoa_total_percent: "70", provider_id: "" },
                { name: "Chocolat Fleur de Cao Barry 70%", protein: "3.5", carbohydrates: "24.5", fat_percent: "42.7", kcal: "572", ig: "25", price:"14.3" , unit: "Kg", category: "Chocolats", sugar_power: "30", alcool_percent: "", cocoa_butter_percent: "42.7",  salt: "",
                water_percent: "", sugar_percent: "30", dry_matter_percent: "100", cocoa_percent: "27.3", cocoa_total_percent: "70", provider_id: "" },
                { name: "Chocolat Ultime 70%", protein: "3.5", carbohydrates: "24.5", fat_percent: "42.7", kcal: "572", ig: "25", price:"14.3" , unit: "Kg", category: "Chocolats", sugar_power: "30", alcool_percent: "", cocoa_butter_percent: "42.7",  salt: "",
                water_percent: "", sugar_percent: "30", dry_matter_percent: "100", cocoa_percent: "27.3", cocoa_total_percent: "70", provider_id: "" },
                { name: "Chocolat Barry Cuba 70%", protein: "3.5", carbohydrates: "24.5", fat_percent: "41.9", kcal: "572", ig: "25", price:"" , unit: "Kg", category: "Chocolats", sugar_power: "30", alcool_percent: "", cocoa_butter_percent: "41.9",  salt: "",
                water_percent: "", sugar_percent: "30", dry_matter_percent: "100", cocoa_percent: "28.1", cocoa_total_percent: "70", provider_id: "" },
                { name: "Chocolat 70.30.42 Callebaut", protein: "3.5", carbohydrates: "24.5", fat_percent: "41.9", kcal: "572", ig: "25", price:"12.4" , unit: "Kg", category: "Chocolats", sugar_power: "30", alcool_percent: "", cocoa_butter_percent: "41.9",  salt: "",
                water_percent: "", sugar_percent: "30", dry_matter_percent: "100", cocoa_percent: "28.1", cocoa_total_percent: "70", provider_id: "" },
                { name: "Chocolat Noir Opéra 70%", protein: "3.5", carbohydrates: "24.5", fat_percent: "41.9", kcal: "572", ig: "25", price:"14.3" , unit: "Kg", category: "Chocolats", sugar_power: "30", alcool_percent: "", cocoa_butter_percent: "41.9",  salt: "",
                water_percent: "", sugar_percent: "30", dry_matter_percent: "100", cocoa_percent: "28.1", cocoa_total_percent: "70", provider_id: "" },
                { name: "Poudre métalisée Or", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Poudre métalisée Irisée Vert", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"12.60" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Poudre métalisée Or Sable", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"12.60" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Poudre métalisée Or Miel", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"12.60" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Poudre métalisée Irisée Jaune", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"12.60" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Poudre métalisée Irisée Rose", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"12.60" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Poudre métalisée Rouge", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"12.60" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Poudre métalisée Bleue", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"12.60" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Poudre métalisée Cuivre", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"12.60" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Poudre métalisée Argent", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"12.60" , unit: "Kg", category: "Décors", sugar_power:"", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Poudre métalisée Bronze", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"12.60" , unit: "Kg", category: "Décors", sugar_power:"", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Poudre métalisée Ruby", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"12.60" , unit: "Kg", category: "Décors", sugar_power:"", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Poudre métalisée Vert", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"12.60" , unit: "Kg", category: "Décors", sugar_power:"", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Colorant Chocolat Orange", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"402.2" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant Chocolat Vert", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"402.2" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
								water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant Chocolat Blanc Titane", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"402.2" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant Chocolat Noir", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"402.2" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
								water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant Chocolat Marron", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"402.2" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant Chocolat Jaune", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"402.2" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
								water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant Chocolat Bleu", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"402.2" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant Chocolat Rouge", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"402.2" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
								water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant Chocolat Violet", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"402.2" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant Chocolat Rose", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"402.2" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
								water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Beurre de cacao coloré Marron", protein: "", carbohydrates: "", fat_percent: "90", kcal: "770", ig: "", price:"84" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "90",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "90", provider_id: "" },
								{ name: "Beurre de cacao coloré Jaune", protein: "", carbohydrates: "", fat_percent: "90", kcal: "770", ig: "", price:"84" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "90",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "90", provider_id: "" },
								{ name: "Beurre de cacao coloré Rose", protein: "", carbohydrates: "", fat_percent: "90", kcal: "770", ig: "", price:"84" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "90",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "90", provider_id: "" },
								{ name: "Beurre de cacao coloré Vert", protein: "", carbohydrates: "", fat_percent: "90", kcal: "770", ig: "", price:"84" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "90",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "90", provider_id: "" },
								{ name: "Beurre de cacao coloré Blanc", protein: "", carbohydrates: "", fat_percent: "90", kcal: "770", ig: "", price:"84" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "90",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "90", provider_id: "" },
								{ name: "Beurre de cacao coloré Bleue", protein: "", carbohydrates: "", fat_percent: "90", kcal: "770", ig: "", price:"84" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "90",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "90", provider_id: "" },
								{ name: "Beurre de cacao coloré Orange", protein: "", carbohydrates: "", fat_percent: "90", kcal: "770", ig: "", price:"84" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "90",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "90", provider_id: "" },
								{ name: "Beurre de cacao coloré Noir", protein: "", carbohydrates: "", fat_percent: "90", kcal: "770", ig: "", price:"84" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "90",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "90", provider_id: "" },
								{ name: "Beurre de cacao coloré Rouge", protein: "", carbohydrates: "", fat_percent: "90", kcal: "770", ig: "", price:"84" , unit: "Kg", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "90",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "90", provider_id: "" },
                { name: "Colorant hydrosoluble Bleu", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"81.6" , unit: "Litre", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "98", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant hydrosoluble Blanc", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"81.6" , unit: "Litre", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "98", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant hydrosoluble Rouge", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"81.6" , unit: "Litre", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "98", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant hydrosoluble Jaune", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"81.6" , unit: "Litre", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "98", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant hydrosoluble Vert", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"81.6" , unit: "Litre", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "98", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant hydrosoluble Violet", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"81.6" , unit: "Litre", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "98", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant hydrosoluble Rose", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"81.6" , unit: "Litre", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "98", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant hydrosoluble Noir", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"81.6" , unit: "Litre", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "98", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant hydrosoluble Marron", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"81.6" , unit: "Litre", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "98", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
								{ name: "Colorant hydrosoluble Orange", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"81.6" , unit: "Litre", category: "Décors", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "98", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Chunks Chocolat au lait", protein: '3.9', carbohydrates: '24.5', fat_percent: '9.2', kcal: '196', ig: '35', price:"23.43" , unit: "Kg", category: "Chocolats", sugar_power: "24.5", alcool_percent: "", cocoa_butter_percent: "6.2",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Chunks Chocolat Noir",  protein: '3.5', carbohydrates: '24.5', fat_percent: '9.6', kcal: '198', ig: '25', price:"18.57" , unit: "Kg", category: "Chocolats", sugar_power: "24.5", alcool_percent: "", cocoa_butter_percent: "6.6",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Chunks Chocolat Blanc", protein: '6.6', carbohydrates: '57.0', fat_percent: '34.0', kcal: '560', ig: "45", price:"20.57" , unit: "Kg", category: "Chocolats", sugar_power: "57", alcool_percent: "", cocoa_butter_percent: "9.3",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Vanille gousse en poudre", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "5", price:"137.2" , unit: "Kg", category: "Épices", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "2", sugar_percent: "", dry_matter_percent: "98", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Baking powder", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"8.27" , unit: "Kg", category: "Additifs", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Gélatine de poisson", protein: '86.0', carbohydrates: '0.0', fat_percent: '0.1', kcal: '344', ig: "", price:"34" , unit: "Kg", category: "Additifs", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "100", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Lécithine de soja", protein: "", carbohydrates: "", fat_percent: "13.6", kcal: "104", ig: "", price:"39.85" , unit: "Kg", category: "Additifs", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "Lécithine de soja en poudre", protein: "", carbohydrates: "", fat_percent: "13.6", kcal: "104", ig: "", price:"41.15" , unit: "Kg", category: "Additifs", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" }
            ])
    rescue
      #flash[:error] = "Erreur lors de la création des ingrédients"
    end
  end
end
