class CreateIngredientsBaseJob < ActiveJob::Base
	queue_as :default

	def perform(user)
		begin
			user.ingredients.create!([  { name: "fraises guariguette", price: "7,25", unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "fraises des bois",price: "12,76" , unit: "Kg",  ingredient_category_attributes: { name: "fruits" } },
										{ name: "bananes",price: "1,99", unit: "Kg",  ingredient_category_attributes: { name: "fruits" } },
										{ name: "oranges",price: "0,95", unit: "Kg",  ingredient_category_attributes: { name: "fruits" } },
										{ name: "pamplemousse",price: "1,10" , unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "kiwi",price: "1,85" , unit: "Kg",  ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de fraises",price: "7,11", unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de bananes",price:"4,99" , unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de citron vert",price:"8,32" , unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de framboise",price: "8,21", unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de cassis",price: "7,30", unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée d'abricot",price:"4,99" , unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de griotte",price:"7,38" , unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de passion",price: "8,20", unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de pomme verte",price:"5,35" , unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de poire williams",price:"5,12", unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "raisins secs",price:"4,50" , unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "abricots sechés",price:"5,35" , unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "abricots moelleux",price:"8,49" , unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "abricots au sirop",price:"4,21" , unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "ananas",price: "2,00", unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "ananas au sirop",price:"4,21" , unit: "Kg", ingredient_category_attributes: { name: "fruits" } },
										{ name: "couverture blanche",price:"9,73" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture café",price:"11,89" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture lait 30%",price:"8,94" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture lait 35%",price:"11,20" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture lait 42%",price:"11,45" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture lait 45%",price:"11,17" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture lait 50%",price:"12,67" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture Madagascar 70%",price:"14,56" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture Cuba 70%",price:"12,52" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture Java 70%",price:"12,40" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture Vietnam 70%",price:"13,55" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture caramel",price:"9,57" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Brésil 70%",price:"13,20" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Papouasie 70%",price:"12,98" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Côte d'Ivoire 70%",price:"8,23" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Pérou 75%",price:"14,35" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Ghana 75%",price:"10,34" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Equateur 80%",price:"11,60" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Porcelana 75%",price:"16,67" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Chua 75%",price:"17,40" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Côte d'Ivoire 65%",price:"7,89" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Côte d'Ivoire 60%",price:"6,50" , unit: "Kg", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Farine T45",price:"0,62" , unit: "Kg", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine T55",price:"0,65" , unit: "Kg", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine T65",price:"0,86" , unit: "Kg", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine de sarrasin bio",price:"2,29" , unit: "Kg", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine de riz",price:"4,07" , unit: "Kg", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Fécule de maïs bio",price:"6,67" , unit: "Kg", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Fécule de pommes de terre",price:"2,95" , unit: "Kg", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine de seigle",price:"1,75" , unit: "Kg", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Flocons d'avoine",price:"2,32" , unit: "Kg", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine de Gruau",price:"1,79" , unit: "Kg", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine T80",price:"1,60" , unit: "Kg", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine T110",price:"1,73" , unit: "Kg", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine T150",price:"1,76" , unit: "Kg", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Dextrose",price:"1,47" , unit: "Kg", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Glucose DE 40",price:"6,50" , unit: "Kg", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Glucose DE 60",price:"7,21" , unit: "Kg", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Sucre inverti",price:"2,58" , unit: "Kg", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Sucre cristal",price:"1,02" , unit: "Kg", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Cassonade",price:"1,68" , unit: "Kg", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Sucre grain",price:"2,11" , unit: "Kg", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Sucre glace",price:"1,40" , unit: "Kg", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Sucre semoule",price:"1,14" , unit: "Kg", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Mélasse",price:"1,05" , unit: "Kg", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Sirop d'érable",price:"21,35" , unit: "Kg", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Stévia",price:"31,48" , unit: "Kg", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Beurre fin",price:"3,20" , unit: "Kg", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Beurre de tourage",price:"6,40" , unit: "Kg", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Lait écrémé",price:"0,94", unit: "Litre", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Lait demi-écrémé",price:"0,89", unit: "Litre", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Lait entier",price:"0,97", unit: "Litre", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Crème liquide",price:"2,36", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Mascarpone",price:"6,90" , unit: "Kg", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Crème fraiche",price:"4,22" , unit: "Kg", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Rose en pâte d'amande",price:"0,96", unit: "Pièce", ingredient_category_attributes: { name: "décors" } },
										{ name: "Rose en sucre",price:"0,99", ingredient_category_attributes: { name: "décors" } },
										{ name: "Ballotin 125g",price:"0,38", unit: "Pièce", ingredient_category_attributes: { name: "emballages" } },
										{ name: "Ballotin 375g",price:"0,47" , unit: "Pièce", ingredient_category_attributes: { name: "emballages" } },
										{ name: "Ballotin 500g",price:"0,52" , unit: "Pièce", ingredient_category_attributes: { name: "emballages" } },
										{ name: "Ballotin 1000g",price:"0,86" , unit: "Pièce", ingredient_category_attributes: { name: "emballages" } },
										{ name: "Boîte pâtissière",price:"0,17" , unit: "Pièce", ingredient_category_attributes: { name: "emballages" } },
										{ name: "Noisettes poudre",price:"13,41" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Noisettes hâchées",price:"12,22" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Noisettes émondées",price:"9,32" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Noisettes entières",price:"9,24" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Amandes poudre",price:"10,32" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Amandes effilées",price:"8,82" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Amandes hâchées",price:"9,55" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Amandes émondées",price:"9,31" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Amandes entières",price:"10,22" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Pistaches émondées",price:"12,95" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Pistaches entières",price:"13,45" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Noix de cajou",price:"11,17" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Noix",price:"10,67" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Noix de pécan",price:"9,80" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Noix du Brésil",price:"10,90" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Cacahuètes",price:"7,33" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Praliné noisettes 40/60",price:"16,63" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Praliné amandes 40/60",price:"15,46" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Praliné amandes et noisettes 50/50",price:"16,12" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Alcool de poire",price:"14,50" , unit: "Litre", ingredient_category_attributes: { name: "divers" } },
										{ name: "Cointreau",price:"17,90" , unit: "Litre", ingredient_category_attributes: { name: "divers" } },
										{ name: "Cognac 40°",price:"27,12" , unit: "Litre", ingredient_category_attributes: { name: "divers" } },
										{ name: "Gingembre confit",price:"11,16" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Gingembre en poudre",price:"10,90" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Gomme arabyque",price:"35,08" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Gélatine en poudre",price:"24,99" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Lait de coco",price:"4,50" , unit: "Litre", ingredient_category_attributes: { name: "divers" } },
										{ name: "Pectine jaune",price:"37,80" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Poudre à crème",price:"4,45" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Sorbitol",price:"8,67" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Thé Earl Grey",price:"32,50" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Acide citrique",price:"8,10" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Acide tartrique",price:"26,90" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Crème de tartre",price:"23,35" , unit: "Kg", ingredient_category_attributes: { name: "divers" } },
										{ name: "Glaçage miroir",price:"8,77" , unit: "Kg", ingredient_category_attributes: { name: "divers" } }])
		rescue
			flash[:error] = "Erreur lors de la création des ingrédients"
		end
	end

end