class CreateBaseRecipeIngredientsJob < ActiveJob::Base
	queue_as :default

	def perform(user)
		begin
			user.ingredients.create!([
                { name: "Chocolat 70.38.30 Callebaut", protein: "3.5", carbohydrates: "24.5", fat_percent: "38", kcal: "572", ig: "25", price:"12.3" , unit: "Kg", category: "Chocolats", sugar_power: "30", alcool_percent: "", cocoa_butter_percent: "38",  salt: "",
                water_percent: "", sugar_percent: "30", dry_matter_percent: "100", cocoa_percent: "32", cocoa_total_percent: "70", provider_id: "" },
                { name: "Chocolat Saint Domingue Barry 70%", protein: "3.5", carbohydrates: "24.5", fat_percent: "41.9", kcal: "572", ig: "25", price:"14.8" , unit: "Kg", category: "Chocolats", sugar_power: "30", alcool_percent: "", cocoa_butter_percent: "41.9",  salt: "",
                water_percent: "", sugar_percent: "30", dry_matter_percent: "100", cocoa_percent: "28.1", cocoa_total_percent: "70", provider_id: "" },
                { name: "Chocolat Fleur de Cao Barry 70%", protein: "3.5", carbohydrates: "24.5", fat_percent: "42.7", kcal: "572", ig: "25", price:"14.3" , unit: "Kg", category: "Chocolats", sugar_power: "30", alcool_percent: "", cocoa_butter_percent: "42.7",  salt: "",
                water_percent: "", sugar_percent: "30", dry_matter_percent: "100", cocoa_percent: "27.3", cocoa_total_percent: "70", provider_id: "" },
                { name: "Chocolat Ultime 70%", protein: "3.5", carbohydrates: "24.5", fat_percent: "42.7", kcal: "572", ig: "25", price:"14.3" , unit: "Kg", category: "Chocolats", sugar_power: "30", alcool_percent: "", cocoa_butter_percent: "42.7",  salt: "",
                water_percent: "", sugar_percent: "30", dry_matter_percent: "100", cocoa_percent: "27.3", cocoa_total_percent: "70", provider_id: "" },
                { name: "Chocolat Barry Cuba 70%", protein: "3.5", carbohydrates: "24.5", fat_percent: "41.9", kcal: "572", ig: "25", price:"" , unit: "Kg", category: "Chocolats", sugar_power: "30", alcool_percent: "", cocoa_butter_percent: "41.9",  salt: "",
                water_percent: "", sugar_percent: "30", dry_matter_percent: "100", cocoa_percent: "28.1", cocoa_total_percent: "70", provider_id: "" },
                { name: "Chocolat 70.30.42 Callebaut", protein: "3.5", carbohydrates: "24.5", fat_percent: "41.9", kcal: "572", ig: "25", price:"12.4" , unit: "Kg", category: "Chocolats", sugar_power: "30", alcool_percent: "", cocoa_butter_percent: "41.9",  salt: "",
                water_percent: "", sugar_percent: "30", dry_matter_percent: "100", cocoa_percent: "28.1", cocoa_total_percent: "70", provider_id: "" },
                { name: "Chocolat Noir Opéra 70%", protein: "3.5", carbohydrates: "24.5", fat_percent: "41.9", kcal: "572", ig: "25", price:"14.3" , unit: "Kg", category: "Chocolats", sugar_power: "30", alcool_percent: "", cocoa_butter_percent: "41.9",  salt: "",
                water_percent: "", sugar_percent: "30", dry_matter_percent: "100", cocoa_percent: "28.1", cocoa_total_percent: "70", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" },
                { name: "", protein: "", carbohydrates: "", fat_percent: "", kcal: "", ig: "", price:"" , unit: "", category: "", sugar_power: "", alcool_percent: "", cocoa_butter_percent: "",  salt: "",
                water_percent: "", sugar_percent: "", dry_matter_percent: "", cocoa_percent: "", cocoa_total_percent: "", provider_id: "" }
            ])
    rescue
      #flash[:error] = "Erreur lors de la création des ingrédients"
    end
  end
end
