class CreateIngredientsBaseJob < ActiveJob::Base
	queue_as :default

	def perform(user)
		begin

			user.ingredients.create!([  { name: "fraises", ingredient_category_attributes: { name: "fruits" } },
										{ name: "fraises des bois", ingredient_category_attributes: { name: "fruits" } },
										{ name: "bananes", ingredient_category_attributes: { name: "fruits" } },
										{ name: "oranges", ingredient_category_attributes: { name: "fruits" } },
										{ name: "pamplemousse", ingredient_category_attributes: { name: "fruits" } },
										{ name: "kiwi", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de fraises", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de bananes", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de citron vert", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de framboise", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de cassis", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée d'abricot", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de griotte", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de passion", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de pomme verte", ingredient_category_attributes: { name: "fruits" } },
										{ name: "purée de poire williams", ingredient_category_attributes: { name: "fruits" } },
										{ name: "raisins secs", ingredient_category_attributes: { name: "fruits" } },
										{ name: "abricots sechés", ingredient_category_attributes: { name: "fruits" } },
										{ name: "abricots moelleux", ingredient_category_attributes: { name: "fruits" } },
										{ name: "abricots au sirop", ingredient_category_attributes: { name: "fruits" } },
										{ name: "ananas", ingredient_category_attributes: { name: "fruits" } },
										{ name: "ananas au sirop", ingredient_category_attributes: { name: "fruits" } },
										{ name: "couverture blanche satin", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture blanche", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture café", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture lait 30%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture lait 35%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture lait 42%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture lait 45%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture lait 50%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture Madagascar 70%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture Cuba 70%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture Java 70%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture Vietnam 70%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "couverture caramel", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Brésil 70%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Papouasie 70%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Côte d'Ivoire 70%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Pérou 75%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Ghana 75%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Equateur 80%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Porcelana 75%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Chua 75%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Côte d'Ivoire 65%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Couverture Côte d'Ivoire 60%", ingredient_category_attributes: { name: "chocolats" } },
										{ name: "Farine T45", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine T55", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine T65", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine de sarrasin", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine de riz", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine de maïs", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Fécule de maïs", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Fécule de pommes de terre", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine de seigle", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Flocons d'avoine", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine de Gruau", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine T80", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine T110", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Farine T150", ingredient_category_attributes: { name: "céréales" } },
										{ name: "Dextrose", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Glucose DE 40", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Glucose DE 60", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Sucre inverti", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Sucre cristal", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Cassonade", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Sucre grain", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Sucre glace", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Sucre semoule", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Mélasse", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Sirop d'érable", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Stévia", ingredient_category_attributes: { name: "sucres" } },
										{ name: "Beurre fin", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Beurre de tourage", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Lait écrémé", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Lait demi-écrémé", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Lait entier", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Crème liquide", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Mascarpone", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Crème fraiche", ingredient_category_attributes: { name: "produits laitiers" } },
										{ name: "Rose en pâte d'amande", ingredient_category_attributes: { name: "décors" } },
										{ name: "Rose en sucre", ingredient_category_attributes: { name: "décors" } },
										{ name: "Ballotin 150g", ingredient_category_attributes: { name: "emballages" } },
										{ name: "Ballotin 350g", ingredient_category_attributes: { name: "emballages" } },
										{ name: "Ballotin 500g", ingredient_category_attributes: { name: "emballages" } },
										{ name: "Ballotin 1000g", ingredient_category_attributes: { name: "emballages" } },
										{ name: "Boîte pâtissière", ingredient_category_attributes: { name: "emballages" } },
										{ name: "Noisettes poudre", ingredient_category_attributes: { name: "divers" } },
										{ name: "Noisettes hâchées", ingredient_category_attributes: { name: "divers" } },
										{ name: "Noisettes émondées", ingredient_category_attributes: { name: "divers" } },
										{ name: "Noisettes entières", ingredient_category_attributes: { name: "divers" } },
										{ name: "Amandes poudre", ingredient_category_attributes: { name: "divers" } },
										{ name: "Amandes effilées", ingredient_category_attributes: { name: "divers" } },
										{ name: "Amandes hâchées", ingredient_category_attributes: { name: "divers" } },
										{ name: "Amandes émondées", ingredient_category_attributes: { name: "divers" } },
										{ name: "Amandes entières", ingredient_category_attributes: { name: "divers" } },
										{ name: "Pistaches émondées", ingredient_category_attributes: { name: "divers" } },
										{ name: "Pistaches entières", ingredient_category_attributes: { name: "divers" } },
										{ name: "Noix de cajou", ingredient_category_attributes: { name: "divers" } },
										{ name: "Noix", ingredient_category_attributes: { name: "divers" } },
										{ name: "Noix de pécan", ingredient_category_attributes: { name: "divers" } },
										{ name: "Noix du Bréil", ingredient_category_attributes: { name: "divers" } },
										{ name: "Cacahuètes", ingredient_category_attributes: { name: "divers" } },
										{ name: "Praliné noisettes 40/60", ingredient_category_attributes: { name: "divers" } },
										{ name: "Praliné amandes 40/60", ingredient_category_attributes: { name: "divers" } },
										{ name: "Praliné amandes et noisettes 50/50", ingredient_category_attributes: { name: "divers" } },
										{ name: "Alcool de poire", ingredient_category_attributes: { name: "divers" } },
										{ name: "Cointreau", ingredient_category_attributes: { name: "divers" } },
										{ name: "Cognac 40°", ingredient_category_attributes: { name: "divers" } },
										{ name: "Gingembre confit", ingredient_category_attributes: { name: "divers" } },
										{ name: "Gingembre en poudre", ingredient_category_attributes: { name: "divers" } },
										{ name: "Gomme arabyque", ingredient_category_attributes: { name: "divers" } },
										{ name: "Gélatine", ingredient_category_attributes: { name: "divers" } },
										{ name: "Lait de coco", ingredient_category_attributes: { name: "divers" } },
										{ name: "Pectine jaune", ingredient_category_attributes: { name: "divers" } },
										{ name: "Poudre à crème", ingredient_category_attributes: { name: "divers" } },
										{ name: "Sorbitol", ingredient_category_attributes: { name: "divers" } },
										{ name: "Thé Earl Grey", ingredient_category_attributes: { name: "divers" } },
										{ name: "Acide citrique", ingredient_category_attributes: { name: "divers" } },
										{ name: "Acide tartrique", ingredient_category_attributes: { name: "divers" } },
										{ name: "Crème de tartre", ingredient_category_attributes: { name: "divers" } },
										{ name: "Glaçage miroir", ingredient_category_attributes: { name: "divers" } }])
		rescue
			flash[:error] = "Erreur lors de la création des ingrédients"
		end
	end

end